


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."consumos_sessao" (
    "id" bigint NOT NULL,
    "id_sessao" bigint,
    "id_preparo" bigint,
    "quantidade_consumida" numeric(10,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."consumos_sessao" OWNER TO "postgres";


ALTER TABLE "public"."consumos_sessao" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."consumos_sessao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."historias" (
    "id" bigint NOT NULL,
    "id_sessao" bigint,
    "titulo_historia" "text" NOT NULL
);


ALTER TABLE "public"."historias" OWNER TO "postgres";


ALTER TABLE "public"."historias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."historias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leituras" (
    "id" bigint NOT NULL,
    "id_sessao" bigint,
    "documento" "text" NOT NULL,
    "leitor" "text" NOT NULL
);


ALTER TABLE "public"."leituras" OWNER TO "postgres";


ALTER TABLE "public"."leituras" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leituras_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."preparos" (
    "id" bigint NOT NULL,
    "data_preparo" "date" NOT NULL,
    "mestre_preparo" "text" NOT NULL,
    "quantidade_preparada" numeric(10,2) NOT NULL,
    "grau" "text",
    "status" "text" DEFAULT 'Disponível'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "tipo" "text" DEFAULT 'Local'::"text",
    "data_chegada" "date",
    "nucleo_origem" "text",
    "procedencia_mariri" "text",
    "procedencia_chacrona" "text",
    "user_id" "uuid",
    CONSTRAINT "preparos_status_check" CHECK (("status" = ANY (ARRAY['Disponível'::"text", 'Esgotado'::"text", 'Em Maturação'::"text"]))),
    CONSTRAINT "preparos_tipo_check" CHECK (("tipo" = ANY (ARRAY['Local'::"text", 'Doação'::"text"])))
);


ALTER TABLE "public"."preparos" OWNER TO "postgres";


ALTER TABLE "public"."preparos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."preparos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."saidas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "data_saida" "date" NOT NULL,
    "quantidade" numeric NOT NULL,
    "destino" "text" NOT NULL,
    "preparo_id" bigint,
    "observacoes" "text"
);


ALTER TABLE "public"."saidas" OWNER TO "postgres";


ALTER TABLE "public"."saidas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."saidas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sessoes" (
    "id" bigint NOT NULL,
    "data_realizacao" timestamp with time zone NOT NULL,
    "tipo" "text" NOT NULL,
    "dirigente" "text" NOT NULL,
    "explanador" "text",
    "quantidade_participantes" integer DEFAULT 0 NOT NULL,
    "id_preparo" bigint,
    "quantidade_consumida" numeric(10,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "leitor_documentos" "text",
    "user_id" "uuid",
    CONSTRAINT "sessoes_tipo_check" CHECK (("tipo" = ANY (ARRAY['Escala'::"text", 'Escala Anual'::"text", 'Casal'::"text", 'Extra'::"text", 'Instrutiva'::"text", 'Da Direção'::"text", 'Quadro de Mestres'::"text", 'Adventício'::"text", 'Preparo'::"text", 'Caráter Instrutivo'::"text"])))
);


ALTER TABLE "public"."sessoes" OWNER TO "postgres";


ALTER TABLE "public"."sessoes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sessoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."visitantes" (
    "id" bigint NOT NULL,
    "id_sessao" bigint,
    "nome" "text" NOT NULL,
    "nucleo_origem" "text"
);


ALTER TABLE "public"."visitantes" OWNER TO "postgres";


ALTER TABLE "public"."visitantes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."visitantes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."consumos_sessao"
    ADD CONSTRAINT "consumos_sessao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."historias"
    ADD CONSTRAINT "historias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leituras"
    ADD CONSTRAINT "leituras_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."preparos"
    ADD CONSTRAINT "preparos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sessoes"
    ADD CONSTRAINT "sessoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."visitantes"
    ADD CONSTRAINT "visitantes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."consumos_sessao"
    ADD CONSTRAINT "consumos_sessao_id_preparo_fkey" FOREIGN KEY ("id_preparo") REFERENCES "public"."preparos"("id");



ALTER TABLE ONLY "public"."consumos_sessao"
    ADD CONSTRAINT "consumos_sessao_id_sessao_fkey" FOREIGN KEY ("id_sessao") REFERENCES "public"."sessoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."historias"
    ADD CONSTRAINT "historias_id_sessao_fkey" FOREIGN KEY ("id_sessao") REFERENCES "public"."sessoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."leituras"
    ADD CONSTRAINT "leituras_id_sessao_fkey" FOREIGN KEY ("id_sessao") REFERENCES "public"."sessoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."preparos"
    ADD CONSTRAINT "preparos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_preparo_id_fkey" FOREIGN KEY ("preparo_id") REFERENCES "public"."preparos"("id");



ALTER TABLE ONLY "public"."sessoes"
    ADD CONSTRAINT "sessoes_id_preparo_fkey" FOREIGN KEY ("id_preparo") REFERENCES "public"."preparos"("id");



ALTER TABLE ONLY "public"."sessoes"
    ADD CONSTRAINT "sessoes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."visitantes"
    ADD CONSTRAINT "visitantes_id_sessao_fkey" FOREIGN KEY ("id_sessao") REFERENCES "public"."sessoes"("id") ON DELETE CASCADE;



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."consumos_sessao" TO "anon";
GRANT ALL ON TABLE "public"."consumos_sessao" TO "authenticated";
GRANT ALL ON TABLE "public"."consumos_sessao" TO "service_role";



GRANT ALL ON SEQUENCE "public"."consumos_sessao_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."consumos_sessao_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."consumos_sessao_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."historias" TO "anon";
GRANT ALL ON TABLE "public"."historias" TO "authenticated";
GRANT ALL ON TABLE "public"."historias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."historias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."historias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."historias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."leituras" TO "anon";
GRANT ALL ON TABLE "public"."leituras" TO "authenticated";
GRANT ALL ON TABLE "public"."leituras" TO "service_role";



GRANT ALL ON SEQUENCE "public"."leituras_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leituras_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leituras_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."preparos" TO "anon";
GRANT ALL ON TABLE "public"."preparos" TO "authenticated";
GRANT ALL ON TABLE "public"."preparos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."preparos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."preparos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."preparos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."saidas" TO "anon";
GRANT ALL ON TABLE "public"."saidas" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sessoes" TO "anon";
GRANT ALL ON TABLE "public"."sessoes" TO "authenticated";
GRANT ALL ON TABLE "public"."sessoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sessoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sessoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sessoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."visitantes" TO "anon";
GRANT ALL ON TABLE "public"."visitantes" TO "authenticated";
GRANT ALL ON TABLE "public"."visitantes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."visitantes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."visitantes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."visitantes_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































