-- Guardião — vários núcleos no mesmo banco e visão regional do Mestre Central.
--
-- • Cada registro passa a pertencer a um núcleo (nucleo_id); os dados existentes
--   ficam no núcleo criado a partir das configurações atuais.
-- • Usuários de núcleo leem e escrevem só o próprio núcleo (RLS).
-- • O administrador passa a ser administrador geral: gerencia regiões, núcleos,
--   usuários, configurações e listas de todos os núcleos.
-- • O Mestre Central não pertence a núcleo; lê os dados da própria região pela
--   função dados_regionais(), sem permissão de escrita.
-- • Configurações são por núcleo; listas do sistema são por região.

-- ============================================================
-- 1. Regiões e núcleos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.regioes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nucleos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  regiao_id bigint NOT NULL REFERENCES public.regioes(id),
  cidade text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (regiao_id, nome)
);

-- Região e núcleo iniciais, a partir das configurações existentes
DO $$
DECLARE
  v_regiao bigint;
  v_nome text;
  v_nome_regiao text;
  v_cidade text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.nucleos) THEN
    SELECT nucleo_nome, nucleo_regiao, nucleo_cidade
      INTO v_nome, v_nome_regiao, v_cidade
      FROM public.configuracoes
      LIMIT 1;

    INSERT INTO public.regioes (nome)
    VALUES (COALESCE(NULLIF(trim(v_nome_regiao), ''), 'Região principal'))
    RETURNING id INTO v_regiao;

    INSERT INTO public.nucleos (nome, regiao_id, cidade)
    VALUES (COALESCE(NULLIF(trim(v_nome), ''), 'Núcleo Jardim Real'), v_regiao, NULLIF(trim(v_cidade), ''));
  END IF;
END $$;

-- ============================================================
-- 2. nucleo_id em todas as tabelas de dados
-- ============================================================
DO $$
DECLARE
  t text;
  v_nucleo bigint := (SELECT min(id) FROM public.nucleos);
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'sessoes', 'preparos', 'saidas', 'consumos_sessao', 'membros',
    'membros_graus_historico', 'leituras', 'historias', 'visitantes'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS nucleo_id bigint REFERENCES public.nucleos(id)', t);
    EXECUTE format('UPDATE public.%I SET nucleo_id = %s WHERE nucleo_id IS NULL', t, v_nucleo);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN nucleo_id SET NOT NULL', t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (nucleo_id)', t || '_nucleo_id_idx', t);
  END LOOP;
END $$;

-- Usuários: núcleo (usuários de núcleo) ou região (Mestre Central)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS nucleo_id bigint REFERENCES public.nucleos(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS regiao_id bigint REFERENCES public.regioes(id);
UPDATE public.profiles
SET nucleo_id = (SELECT min(id) FROM public.nucleos)
WHERE nucleo_id IS NULL AND regiao_id IS NULL;

ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS nucleo_id bigint;
UPDATE public.activity_logs SET nucleo_id = (SELECT min(id) FROM public.nucleos) WHERE nucleo_id IS NULL;
CREATE INDEX IF NOT EXISTS activity_logs_nucleo_idx ON public.activity_logs (nucleo_id, created_at DESC);

-- ============================================================
-- 3. Configurações por núcleo
-- ============================================================
ALTER TABLE public.configuracoes ADD COLUMN IF NOT EXISTS nucleo_id bigint REFERENCES public.nucleos(id) ON DELETE CASCADE;
UPDATE public.configuracoes SET nucleo_id = (SELECT min(id) FROM public.nucleos) WHERE nucleo_id IS NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'configuracoes' AND column_name = 'id'
  ) THEN
    ALTER TABLE public.configuracoes DROP CONSTRAINT IF EXISTS configuracoes_pkey;
    ALTER TABLE public.configuracoes DROP COLUMN id;
    ALTER TABLE public.configuracoes ALTER COLUMN nucleo_id SET NOT NULL;
    ALTER TABLE public.configuracoes ADD PRIMARY KEY (nucleo_id);
  END IF;
END $$;

-- Nome, região e cidade agora ficam na tabela nucleos
ALTER TABLE public.configuracoes DROP COLUMN IF EXISTS nucleo_nome;
ALTER TABLE public.configuracoes DROP COLUMN IF EXISTS nucleo_regiao;
ALTER TABLE public.configuracoes DROP COLUMN IF EXISTS nucleo_cidade;

-- Todo núcleo novo nasce com configurações padrão
CREATE OR REPLACE FUNCTION public.criar_configuracoes_nucleo()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.configuracoes (nucleo_id) VALUES (NEW.id) ON CONFLICT (nucleo_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_criar_configuracoes_nucleo ON public.nucleos;
CREATE TRIGGER trg_criar_configuracoes_nucleo
  AFTER INSERT ON public.nucleos
  FOR EACH ROW EXECUTE FUNCTION public.criar_configuracoes_nucleo();

INSERT INTO public.configuracoes (nucleo_id)
SELECT id FROM public.nucleos
ON CONFLICT (nucleo_id) DO NOTHING;

-- ============================================================
-- 4. Listas do sistema por região
-- ============================================================
ALTER TABLE public.listas_sistema ADD COLUMN IF NOT EXISTS regiao_id bigint REFERENCES public.regioes(id) ON DELETE CASCADE;
UPDATE public.listas_sistema SET regiao_id = (SELECT min(id) FROM public.regioes) WHERE regiao_id IS NULL;
ALTER TABLE public.listas_sistema ALTER COLUMN regiao_id SET NOT NULL;
ALTER TABLE public.listas_sistema DROP CONSTRAINT IF EXISTS listas_sistema_lista_nome_key;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'listas_sistema_regiao_lista_nome_key') THEN
    ALTER TABLE public.listas_sistema
      ADD CONSTRAINT listas_sistema_regiao_lista_nome_key UNIQUE (regiao_id, lista, nome);
  END IF;
END $$;

-- Toda região nova nasce com as listas padrão
CREATE OR REPLACE FUNCTION public.semear_listas_regiao()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.listas_sistema (regiao_id, lista, nome, ordem)
  SELECT NEW.id, l.lista, l.nome, l.ordem
  FROM (VALUES
    ('tipos_sessao', 'Escala', 1), ('tipos_sessao', 'Escala Anual', 2), ('tipos_sessao', 'Casal', 3),
    ('tipos_sessao', 'Extra', 4), ('tipos_sessao', 'Instrutiva', 5), ('tipos_sessao', 'Da Direção', 6),
    ('tipos_sessao', 'Quadro de Mestres', 7), ('tipos_sessao', 'Adventício', 8), ('tipos_sessao', 'Preparo', 9),
    ('tipos_sessao', 'Caráter Instrutivo', 10),
    ('graus', 'Mestre', 1), ('graus', 'Corpo do Conselho', 2), ('graus', 'Corpo Instrutivo', 3), ('graus', 'Sócio', 4),
    ('tipos_delegacao', 'Transmissão da Assistência', 1), ('tipos_delegacao', 'Transmissão da Representação', 2),
    ('motivos_saida', 'Doação', 1), ('motivos_saida', 'Empréstimo', 2), ('motivos_saida', 'Envio para preparo', 3),
    ('motivos_saida', 'Outro', 4)
  ) AS l(lista, nome, ordem)
  ON CONFLICT (regiao_id, lista, nome) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_semear_listas_regiao ON public.regioes;
CREATE TRIGGER trg_semear_listas_regiao
  AFTER INSERT ON public.regioes
  FOR EACH ROW EXECUTE FUNCTION public.semear_listas_regiao();

-- ============================================================
-- 5. Funções de escopo
-- ============================================================
CREATE OR REPLACE FUNCTION public.meu_nucleo()
RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT nucleo_id FROM public.profiles WHERE id = auth.uid()
$$;

CREATE OR REPLACE FUNCTION public.minha_regiao()
RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(p.regiao_id, n.regiao_id)
  FROM public.profiles p
  LEFT JOIN public.nucleos n ON n.id = p.nucleo_id
  WHERE p.id = auth.uid()
$$;

CREATE OR REPLACE FUNCTION public.eh_central()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND status = 'ativo' AND role::text = 'central'
  )
$$;

-- Registros novos herdam o núcleo de quem cria (ou do registro pai)
CREATE OR REPLACE FUNCTION public.definir_nucleo()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.nucleo_id IS NULL THEN
    NEW.nucleo_id := public.meu_nucleo();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.herdar_nucleo_sessao()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.nucleo_id IS NULL THEN
    SELECT nucleo_id INTO NEW.nucleo_id FROM public.sessoes WHERE id = NEW.id_sessao;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.herdar_nucleo_membro()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.nucleo_id IS NULL THEN
    SELECT nucleo_id INTO NEW.nucleo_id FROM public.membros WHERE id = NEW.membro_id;
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sessoes', 'preparos', 'saidas', 'membros'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_definir_nucleo ON public.%I', t);
    EXECUTE format('CREATE TRIGGER trg_definir_nucleo BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.definir_nucleo()', t);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['consumos_sessao', 'leituras', 'historias', 'visitantes'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_definir_nucleo ON public.%I', t);
    EXECUTE format('CREATE TRIGGER trg_definir_nucleo BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.herdar_nucleo_sessao()', t);
  END LOOP;
END $$;

DROP TRIGGER IF EXISTS trg_definir_nucleo ON public.membros_graus_historico;
CREATE TRIGGER trg_definir_nucleo
  BEFORE INSERT ON public.membros_graus_historico
  FOR EACH ROW EXECUTE FUNCTION public.herdar_nucleo_membro();

-- ============================================================
-- 6. Regras de acesso (RLS)
-- ============================================================
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'sessoes', 'preparos', 'saidas', 'consumos_sessao', 'membros',
    'membros_graus_historico', 'leituras', 'historias', 'visitantes'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "Enable read access for all authenticated users" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Enable write access for editors" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Users can read all membros" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Leitura para autenticados" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Escrita para editores" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Leitura do próprio núcleo" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Escrita por editores do núcleo" ON public.%I', t);

    EXECUTE format(
      'CREATE POLICY "Leitura do próprio núcleo" ON public.%I FOR SELECT TO authenticated
       USING (nucleo_id = public.meu_nucleo())', t);
    EXECUTE format(
      'CREATE POLICY "Escrita por editores do núcleo" ON public.%I FOR ALL TO authenticated
       USING (public.can_edit() AND nucleo_id = public.meu_nucleo())
       WITH CHECK (public.can_edit() AND nucleo_id = public.meu_nucleo())', t);
  END LOOP;
END $$;

-- Perfis: o próprio, os do mesmo núcleo, e todos para o administrador geral
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "Perfis visíveis" ON public.profiles;
CREATE POLICY "Perfis visíveis" ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_admin() OR (nucleo_id IS NOT NULL AND nucleo_id = public.meu_nucleo()));

-- Regiões e núcleos: nomes visíveis a todos; alteração só pelo administrador geral
ALTER TABLE public.regioes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nucleos ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.regioes, public.nucleos TO authenticated;

DROP POLICY IF EXISTS "Leitura para autenticados" ON public.regioes;
DROP POLICY IF EXISTS "Escrita pelo administrador geral" ON public.regioes;
CREATE POLICY "Leitura para autenticados" ON public.regioes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Escrita pelo administrador geral" ON public.regioes FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Leitura para autenticados" ON public.nucleos;
DROP POLICY IF EXISTS "Escrita pelo administrador geral" ON public.nucleos;
CREATE POLICY "Leitura para autenticados" ON public.nucleos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Escrita pelo administrador geral" ON public.nucleos FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Configurações: o próprio núcleo; administrador geral vê e altera todas
DROP POLICY IF EXISTS "Leitura para autenticados" ON public.configuracoes;
DROP POLICY IF EXISTS "Alteração por administradores" ON public.configuracoes;
DROP POLICY IF EXISTS "Leitura do próprio núcleo" ON public.configuracoes;
CREATE POLICY "Leitura do próprio núcleo" ON public.configuracoes FOR SELECT TO authenticated
  USING (nucleo_id = public.meu_nucleo() OR public.is_admin());
CREATE POLICY "Alteração por administradores" ON public.configuracoes FOR UPDATE TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Listas: a própria região; administrador geral vê e altera todas
DROP POLICY IF EXISTS "Leitura para autenticados" ON public.listas_sistema;
DROP POLICY IF EXISTS "Escrita por administradores" ON public.listas_sistema;
DROP POLICY IF EXISTS "Leitura da própria região" ON public.listas_sistema;
CREATE POLICY "Leitura da própria região" ON public.listas_sistema FOR SELECT TO authenticated
  USING (regiao_id = public.minha_regiao() OR public.is_admin());
CREATE POLICY "Escrita por administradores" ON public.listas_sistema FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ============================================================
-- 7. Proteção de papel, núcleo e região dos usuários
-- ============================================================
CREATE OR REPLACE FUNCTION public.proteger_campos_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NOT NULL
     AND NOT public.is_admin()
     AND (NEW.role IS DISTINCT FROM OLD.role
          OR NEW.status IS DISTINCT FROM OLD.status
          OR NEW.membro_id IS DISTINCT FROM OLD.membro_id
          OR NEW.nucleo_id IS DISTINCT FROM OLD.nucleo_id
          OR NEW.regiao_id IS DISTINCT FROM OLD.regiao_id) THEN
    RAISE EXCEPTION 'Somente administradores podem alterar papel, situação, núcleo ou vínculo de usuários';
  END IF;
  RETURN NEW;
END;
$$;

DROP FUNCTION IF EXISTS public.admin_listar_usuarios();
CREATE FUNCTION public.admin_listar_usuarios()
RETURNS TABLE (
  id uuid,
  full_name text,
  email text,
  role public.user_role,
  status text,
  membro_id bigint,
  nucleo_id bigint,
  regiao_id bigint,
  criado_em timestamptz,
  ultimo_acesso timestamptz,
  provedor text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  RETURN QUERY
  SELECT p.id, p.full_name, p.email, p.role, p.status, p.membro_id, p.nucleo_id, p.regiao_id,
         u.created_at, u.last_sign_in_at, (u.raw_app_meta_data->>'provider')::text
  FROM public.profiles p
  JOIN auth.users u ON u.id = p.id
  ORDER BY p.full_name NULLS LAST;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_listar_usuarios() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_listar_usuarios() TO authenticated;

-- ============================================================
-- 8. Dados da região para o Mestre Central (somente leitura)
-- ============================================================
CREATE OR REPLACE FUNCTION public.dados_regionais(p_regiao_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_regiao bigint;
  v_nucleos bigint[];
BEGIN
  IF public.eh_central() THEN
    -- O Central só enxerga a própria região, qualquer que seja o parâmetro
    v_regiao := public.minha_regiao();
  ELSIF public.is_admin() THEN
    v_regiao := COALESCE(p_regiao_id, public.minha_regiao());
  ELSE
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  SELECT COALESCE(array_agg(id), '{}') INTO v_nucleos FROM public.nucleos WHERE regiao_id = v_regiao;

  RETURN jsonb_build_object(
    'regiao', (SELECT to_jsonb(r) FROM public.regioes r WHERE r.id = v_regiao),
    'nucleos', COALESCE((
      SELECT jsonb_agg(to_jsonb(n) || jsonb_build_object('configuracao', to_jsonb(c)) ORDER BY n.nome)
      FROM public.nucleos n
      LEFT JOIN public.configuracoes c ON c.nucleo_id = n.id
      WHERE n.regiao_id = v_regiao
    ), '[]'::jsonb),
    'sessoes', COALESCE((SELECT jsonb_agg(to_jsonb(s)) FROM public.sessoes s WHERE s.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'consumos', COALESCE((SELECT jsonb_agg(to_jsonb(c)) FROM public.consumos_sessao c WHERE c.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'preparos', COALESCE((SELECT jsonb_agg(to_jsonb(p)) FROM public.preparos p WHERE p.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'saidas', COALESCE((SELECT jsonb_agg(to_jsonb(s)) FROM public.saidas s WHERE s.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'membros', COALESCE((SELECT jsonb_agg(to_jsonb(m)) FROM public.membros m WHERE m.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'leituras', COALESCE((SELECT jsonb_agg(to_jsonb(l)) FROM public.leituras l WHERE l.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'historias', COALESCE((SELECT jsonb_agg(to_jsonb(h)) FROM public.historias h WHERE h.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'visitantes', COALESCE((SELECT jsonb_agg(to_jsonb(v)) FROM public.visitantes v WHERE v.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'graus', COALESCE((SELECT jsonb_agg(to_jsonb(g)) FROM public.membros_graus_historico g WHERE g.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'responsaveis', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('nucleo_id', p.nucleo_id, 'nome', p.full_name, 'papel', p.role))
      FROM public.profiles p
      WHERE p.nucleo_id = ANY (v_nucleos) AND p.status = 'ativo' AND p.role::text IN ('representante', 'assistente')
    ), '[]'::jsonb)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.dados_regionais(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.dados_regionais(bigint) TO authenticated;

-- ============================================================
-- 9. Auditoria: núcleo do registro e novas tabelas
-- ============================================================
CREATE OR REPLACE FUNCTION public.mensagem_atividade(p_op text, p_tabela text, p_row jsonb)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    (CASE p_op WHEN 'INSERT' THEN 'Criou' WHEN 'UPDATE' THEN 'Editou' ELSE 'Excluiu' END)
    || ' ' ||
    CASE p_tabela
      WHEN 'sessoes' THEN 'sessão (' || COALESCE(p_row->>'tipo', '—') || ')'
      WHEN 'preparos' THEN 'preparo (' || COALESCE(p_row->>'mestre_preparo', '—') || ')'
      WHEN 'saidas' THEN 'saída para ' || COALESCE(p_row->>'destino', '—')
      WHEN 'consumos_sessao' THEN 'consumo de sessão'
      WHEN 'membros' THEN 'membro ' || COALESCE(p_row->>'nome', '—')
      WHEN 'membros_graus_historico' THEN 'mudança de grau (' || COALESCE(p_row->>'grau_novo', '—') || ')'
      WHEN 'leituras' THEN 'leitura de documento (' || COALESCE(p_row->>'documento', '—') || ')'
      WHEN 'historias' THEN 'história contada (' || COALESCE(p_row->>'titulo_historia', '—') || ')'
      WHEN 'visitantes' THEN 'visitante ' || COALESCE(p_row->>'nome', '—')
      WHEN 'configuracoes' THEN 'configurações do núcleo'
      WHEN 'listas_sistema' THEN 'item de lista (' || COALESCE(p_row->>'nome', '—') || ')'
      WHEN 'profiles' THEN 'usuário ' || COALESCE(p_row->>'full_name', p_row->>'email', '—')
      WHEN 'regioes' THEN 'região ' || COALESCE(p_row->>'nome', '—')
      WHEN 'nucleos' THEN 'núcleo ' || COALESCE(p_row->>'nome', '—')
      ELSE p_tabela
    END;
$$;

CREATE OR REPLACE FUNCTION public.log_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb;
  v_new jsonb;
  v_row jsonb;
  v_id text;
  v_nucleo text;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') THEN v_old := to_jsonb(OLD); END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') THEN v_new := to_jsonb(NEW); END IF;

  IF TG_OP = 'UPDATE'
     AND (v_old - 'motivo_alteracao' - 'updated_at') = (v_new - 'motivo_alteracao' - 'updated_at') THEN
    RETURN NEW;
  END IF;

  v_row := COALESCE(v_new, v_old);
  v_id := v_row->>'id';
  v_nucleo := COALESCE(v_row->>'nucleo_id', CASE WHEN TG_TABLE_NAME = 'nucleos' THEN v_id END);

  INSERT INTO public.activity_logs (
    user_id, acao, tabela_afetada, registro_id, registro_uuid,
    dados_antigos, dados_novos, mensagem_automatica, motivo, nucleo_id
  )
  VALUES (
    auth.uid(),
    TG_OP,
    TG_TABLE_NAME,
    CASE WHEN v_id ~ '^[0-9]+$' THEN v_id::bigint END,
    CASE WHEN v_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN v_id::uuid END,
    v_old,
    v_new,
    public.mensagem_atividade(TG_OP, TG_TABLE_NAME, v_row),
    NULLIF(v_new->>'motivo_alteracao', ''),
    CASE WHEN v_nucleo ~ '^[0-9]+$' THEN v_nucleo::bigint END
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_regioes ON public.regioes;
CREATE TRIGGER trg_log_regioes AFTER INSERT OR UPDATE OR DELETE ON public.regioes
  FOR EACH ROW EXECUTE FUNCTION public.log_activity();

DROP TRIGGER IF EXISTS trg_log_nucleos ON public.nucleos;
CREATE TRIGGER trg_log_nucleos AFTER INSERT OR UPDATE OR DELETE ON public.nucleos
  FOR EACH ROW EXECUTE FUNCTION public.log_activity();
