-- Guardião v2 — configurações do núcleo e listas editáveis do sistema.

-- ============================================================
-- Configurações (linha única, id = 1)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.configuracoes (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  nucleo_nome text NOT NULL DEFAULT 'Núcleo Jardim Real',
  nucleo_regiao text,
  nucleo_cidade text,
  logo_arquivo text,
  estoque_minimo_litros numeric(10,2) NOT NULL DEFAULT 10,
  dias_lote_parado integer NOT NULL DEFAULT 90,
  somar_maturacao_no_saldo boolean NOT NULL DEFAULT false,
  calendario_padrao text,
  exigir_leitor_explanador boolean NOT NULL DEFAULT true,
  assinatura_relatorio text,
  resumo_mensal_email boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.configuracoes (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, UPDATE ON public.configuracoes TO authenticated;

DROP POLICY IF EXISTS "Leitura para autenticados" ON public.configuracoes;
DROP POLICY IF EXISTS "Alteração por administradores" ON public.configuracoes;
CREATE POLICY "Leitura para autenticados" ON public.configuracoes
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Alteração por administradores" ON public.configuracoes
  FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ============================================================
-- Listas do sistema
-- ============================================================
CREATE TABLE IF NOT EXISTS public.listas_sistema (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lista text NOT NULL CHECK (lista IN (
    'tipos_sessao', 'graus', 'tipos_delegacao', 'documentos',
    'historias', 'nucleos', 'motivos_saida'
  )),
  nome text NOT NULL,
  ordem integer NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  cor text,
  exige_explanador boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lista, nome)
);

CREATE INDEX IF NOT EXISTS listas_sistema_lista_idx ON public.listas_sistema(lista, ordem);

ALTER TABLE public.listas_sistema ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.listas_sistema TO authenticated;

DROP POLICY IF EXISTS "Leitura para autenticados" ON public.listas_sistema;
DROP POLICY IF EXISTS "Escrita por administradores" ON public.listas_sistema;
CREATE POLICY "Leitura para autenticados" ON public.listas_sistema
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Escrita por administradores" ON public.listas_sistema
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Valores iniciais — espelham lib/constants.ts
INSERT INTO public.listas_sistema (lista, nome, ordem) VALUES
  ('tipos_sessao', 'Escala', 1),
  ('tipos_sessao', 'Escala Anual', 2),
  ('tipos_sessao', 'Casal', 3),
  ('tipos_sessao', 'Extra', 4),
  ('tipos_sessao', 'Instrutiva', 5),
  ('tipos_sessao', 'Da Direção', 6),
  ('tipos_sessao', 'Quadro de Mestres', 7),
  ('tipos_sessao', 'Adventício', 8),
  ('tipos_sessao', 'Preparo', 9),
  ('tipos_sessao', 'Caráter Instrutivo', 10),
  ('graus', 'Mestre', 1),
  ('graus', 'Corpo do Conselho', 2),
  ('graus', 'Corpo Instrutivo', 3),
  ('graus', 'Sócio', 4),
  ('tipos_delegacao', 'Transmissão da Assistência', 1),
  ('tipos_delegacao', 'Transmissão da Representação', 2),
  ('motivos_saida', 'Doação', 1),
  ('motivos_saida', 'Empréstimo', 2),
  ('motivos_saida', 'Envio para preparo', 3),
  ('motivos_saida', 'Outro', 4)
ON CONFLICT (lista, nome) DO NOTHING;
