-- ============================================================
-- Chamadas
-- Catálogo de chamadas (nome e autor) na lista "chamadas" e as chamadas
-- feitas em cada sessão, com quem fez. Substitui a tabela "leituras" e a lista
-- "documentos": o documento lido na sessão é sempre o mesmo, e o leitor
-- continua em sessoes.leitor_documentos.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Catálogo: lista "chamadas" com autor
-- ------------------------------------------------------------
ALTER TABLE public.listas_sistema ADD COLUMN IF NOT EXISTS autor text;

DELETE FROM public.listas_sistema WHERE lista = 'documentos';

DO $$
DECLARE
  c text;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.listas_sistema'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%tipos_sessao%'
  LOOP
    EXECUTE format('ALTER TABLE public.listas_sistema DROP CONSTRAINT %I', c);
  END LOOP;
END $$;

ALTER TABLE public.listas_sistema ADD CONSTRAINT listas_sistema_lista_check CHECK (
  lista IN ('tipos_sessao', 'graus', 'tipos_delegacao', 'chamadas', 'historias', 'nucleos', 'motivos_saida')
);

-- ------------------------------------------------------------
-- 2. Chamadas feitas nas sessões
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chamadas_sessao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sessao bigint NOT NULL REFERENCES public.sessoes(id) ON DELETE CASCADE,
  nucleo_id bigint NOT NULL REFERENCES public.nucleos(id),
  chamada text NOT NULL,
  autor text,
  pessoa text,
  membro_id bigint REFERENCES public.membros(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.chamadas_sessao IS 'Chamadas feitas em cada sessão e quem fez cada uma';
COMMENT ON COLUMN public.chamadas_sessao.autor IS 'Autor da chamada no momento do registro (cópia do catálogo)';
COMMENT ON COLUMN public.chamadas_sessao.pessoa IS 'Nome de quem fez a chamada, como aparece no formulário';

CREATE INDEX IF NOT EXISTS chamadas_sessao_id_sessao_idx ON public.chamadas_sessao(id_sessao);
CREATE INDEX IF NOT EXISTS chamadas_sessao_membro_id_idx ON public.chamadas_sessao(membro_id);
CREATE INDEX IF NOT EXISTS chamadas_sessao_nucleo_id_idx ON public.chamadas_sessao(nucleo_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.chamadas_sessao TO authenticated;

DROP TRIGGER IF EXISTS trg_definir_nucleo ON public.chamadas_sessao;
CREATE TRIGGER trg_definir_nucleo
  BEFORE INSERT ON public.chamadas_sessao
  FOR EACH ROW EXECUTE FUNCTION public.herdar_nucleo_sessao();

ALTER TABLE public.chamadas_sessao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Leitura do próprio núcleo" ON public.chamadas_sessao;
DROP POLICY IF EXISTS "Escrita por editores do núcleo" ON public.chamadas_sessao;
CREATE POLICY "Leitura do próprio núcleo" ON public.chamadas_sessao FOR SELECT TO authenticated
  USING (nucleo_id = public.meu_nucleo());
CREATE POLICY "Escrita por editores do núcleo" ON public.chamadas_sessao FOR ALL TO authenticated
  USING (public.can_edit() AND nucleo_id = public.meu_nucleo())
  WITH CHECK (public.can_edit() AND nucleo_id = public.meu_nucleo());

DROP TRIGGER IF EXISTS trg_log_chamadas_sessao ON public.chamadas_sessao;
CREATE TRIGGER trg_log_chamadas_sessao AFTER INSERT OR UPDATE OR DELETE ON public.chamadas_sessao
  FOR EACH ROW EXECUTE FUNCTION public.log_activity();

-- ------------------------------------------------------------
-- 3. Remove a tabela de leituras por documento (só se estiver vazia)
-- ------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('public.leituras') IS NOT NULL AND EXISTS (SELECT 1 FROM public.leituras) THEN
    RAISE EXCEPTION 'A tabela leituras tem registros; migre-os antes de removê-la';
  END IF;
END $$;

DROP TABLE IF EXISTS public.leituras;

-- ------------------------------------------------------------
-- 4. Visão regional: chamadas no lugar das leituras
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.dados_regionais(p_regiao_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_regiao bigint;
  v_nucleos bigint[];
BEGIN
  IF public.eh_central() THEN
    -- O Central só enxerga a própria região, qualquer que seja o parâmetro
    v_regiao := public.minha_regiao();
  ELSIF public.is_admin() THEN
    v_regiao := COALESCE(p_regiao_id, public.minha_regiao());
  ELSE
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  SELECT COALESCE(array_agg(id), '{}') INTO v_nucleos FROM public.nucleos WHERE regiao_id = v_regiao;

  RETURN jsonb_build_object(
    'regiao', (SELECT to_jsonb(r) FROM public.regioes r WHERE r.id = v_regiao),
    'nucleos', COALESCE((
      SELECT jsonb_agg(to_jsonb(n) || jsonb_build_object('configuracao', to_jsonb(c)) ORDER BY n.nome)
      FROM public.nucleos n
      LEFT JOIN public.configuracoes c ON c.nucleo_id = n.id
      WHERE n.regiao_id = v_regiao
    ), '[]'::jsonb),
    'sessoes', COALESCE((SELECT jsonb_agg(to_jsonb(s)) FROM public.sessoes s WHERE s.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'consumos', COALESCE((SELECT jsonb_agg(to_jsonb(c)) FROM public.consumos_sessao c WHERE c.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'preparos', COALESCE((SELECT jsonb_agg(to_jsonb(p)) FROM public.preparos p WHERE p.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'saidas', COALESCE((SELECT jsonb_agg(to_jsonb(s)) FROM public.saidas s WHERE s.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'membros', COALESCE((SELECT jsonb_agg(to_jsonb(m)) FROM public.membros m WHERE m.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'chamadas', COALESCE((SELECT jsonb_agg(to_jsonb(ch)) FROM public.chamadas_sessao ch WHERE ch.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'historias', COALESCE((SELECT jsonb_agg(to_jsonb(h)) FROM public.historias h WHERE h.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'visitantes', COALESCE((SELECT jsonb_agg(to_jsonb(v)) FROM public.visitantes v WHERE v.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'graus', COALESCE((SELECT jsonb_agg(to_jsonb(g)) FROM public.membros_graus_historico g WHERE g.nucleo_id = ANY (v_nucleos)), '[]'::jsonb),
    'responsaveis', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('nucleo_id', p.nucleo_id, 'nome', p.full_name, 'papel', p.role))
      FROM public.profiles p
      WHERE p.nucleo_id = ANY (v_nucleos) AND p.status = 'ativo' AND p.role::text IN ('representante', 'assistente')
    ), '[]'::jsonb)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.dados_regionais(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.dados_regionais(bigint) TO authenticated;

-- ------------------------------------------------------------
-- 5. Auditoria: mensagem das chamadas
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.mensagem_atividade(p_op text, p_tabela text, p_row jsonb)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT
    (CASE p_op WHEN 'INSERT' THEN 'Criou' WHEN 'UPDATE' THEN 'Editou' ELSE 'Excluiu' END)
    || ' ' ||
    CASE p_tabela
      WHEN 'sessoes' THEN 'sessão (' || COALESCE(p_row->>'tipo', '—') || ')'
      WHEN 'preparos' THEN 'preparo (' || COALESCE(p_row->>'mestre_preparo', '—') || ')'
      WHEN 'saidas' THEN 'saída para ' || COALESCE(p_row->>'destino', '—')
      WHEN 'consumos_sessao' THEN 'consumo de sessão'
      WHEN 'membros' THEN 'membro ' || COALESCE(p_row->>'nome', '—')
      WHEN 'membros_graus_historico' THEN 'mudança de grau (' || COALESCE(p_row->>'grau_novo', '—') || ')'
      WHEN 'chamadas_sessao' THEN 'chamada (' || COALESCE(p_row->>'chamada', '—') || ')'
      WHEN 'historias' THEN 'história contada (' || COALESCE(p_row->>'titulo_historia', '—') || ')'
      WHEN 'visitantes' THEN 'visitante ' || COALESCE(p_row->>'nome', '—')
      WHEN 'configuracoes' THEN 'configurações do núcleo'
      WHEN 'listas_sistema' THEN 'item de lista (' || COALESCE(p_row->>'nome', '—') || ')'
      WHEN 'profiles' THEN 'usuário ' || COALESCE(p_row->>'full_name', p_row->>'email', '—')
      WHEN 'regioes' THEN 'região ' || COALESCE(p_row->>'nome', '—')
      WHEN 'nucleos' THEN 'núcleo ' || COALESCE(p_row->>'nome', '—')
      ELSE p_tabela
    END;
$$;
