-- Guardião v2 — campos novos exigidos pela reestruturação das telas.
-- Idempotente: pode ser executado mais de uma vez.

-- ============================================================
-- Preparos: ciclo de maturação e observações
-- ============================================================
ALTER TABLE public.preparos ADD COLUMN IF NOT EXISTS data_liberacao date;
ALTER TABLE public.preparos ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.preparos ADD COLUMN IF NOT EXISTS motivo_alteracao text;

-- ============================================================
-- Saídas: motivo e tipo de destino
-- ============================================================
ALTER TABLE public.saidas ADD COLUMN IF NOT EXISTS motivo text;
ALTER TABLE public.saidas ADD COLUMN IF NOT EXISTS tipo_destino text DEFAULT 'Núcleo';
ALTER TABLE public.saidas ADD COLUMN IF NOT EXISTS motivo_alteracao text;

ALTER TABLE public.saidas DROP CONSTRAINT IF EXISTS saidas_tipo_destino_check;
ALTER TABLE public.saidas ADD CONSTRAINT saidas_tipo_destino_check
  CHECK (tipo_destino IS NULL OR tipo_destino IN ('Núcleo', 'Pessoa'));

-- ============================================================
-- Sessões: observações, registro histórico e motivo de alteração
-- ============================================================
ALTER TABLE public.sessoes ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE public.sessoes ADD COLUMN IF NOT EXISTS data_aproximada boolean NOT NULL DEFAULT false;
ALTER TABLE public.sessoes ADD COLUMN IF NOT EXISTS fonte_registro text;
ALTER TABLE public.sessoes ADD COLUMN IF NOT EXISTS ata_arquivo text;
ALTER TABLE public.sessoes ADD COLUMN IF NOT EXISTS motivo_alteracao text;

ALTER TABLE public.sessoes DROP CONSTRAINT IF EXISTS sessoes_fonte_registro_check;
ALTER TABLE public.sessoes ADD CONSTRAINT sessoes_fonte_registro_check
  CHECK (fonte_registro IS NULL OR fonte_registro IN ('Livro de atas', 'Relato oral', 'Outro'));

-- Os tipos de sessão passam a ser configuráveis (tabela listas_sistema).
ALTER TABLE public.sessoes DROP CONSTRAINT IF EXISTS sessoes_tipo_check;

-- ============================================================
-- Leituras, histórias e visitantes da sessão
-- ============================================================
-- O leitor pode ser só o vínculo com o membro (leitor_id), sem texto.
ALTER TABLE public.leituras ALTER COLUMN leitor DROP NOT NULL;

ALTER TABLE public.visitantes
  ADD COLUMN IF NOT EXISTS membro_id bigint REFERENCES public.membros(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS leituras_id_sessao_idx ON public.leituras(id_sessao);
CREATE INDEX IF NOT EXISTS leituras_leitor_id_idx ON public.leituras(leitor_id);
CREATE INDEX IF NOT EXISTS historias_id_sessao_idx ON public.historias(id_sessao);
CREATE INDEX IF NOT EXISTS visitantes_id_sessao_idx ON public.visitantes(id_sessao);
CREATE INDEX IF NOT EXISTS preparos_mestre_preparo_id_idx ON public.preparos(mestre_preparo_id);

-- ============================================================
-- Membros: datas, foto e trajetória de graus
-- ============================================================
ALTER TABLE public.membros ADD COLUMN IF NOT EXISTS data_ingresso date;
ALTER TABLE public.membros ADD COLUMN IF NOT EXISTS data_nascimento date;
ALTER TABLE public.membros ADD COLUMN IF NOT EXISTS foto_arquivo text;

CREATE TABLE IF NOT EXISTS public.membros_graus_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membro_id bigint NOT NULL REFERENCES public.membros(id) ON DELETE CASCADE,
  grau_anterior text,
  grau_novo text NOT NULL,
  data date NOT NULL,
  user_id uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS membros_graus_historico_membro_idx
  ON public.membros_graus_historico(membro_id, data DESC);

ALTER TABLE public.membros_graus_historico ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.membros_graus_historico TO authenticated;

DROP POLICY IF EXISTS "Leitura para autenticados" ON public.membros_graus_historico;
DROP POLICY IF EXISTS "Escrita para editores" ON public.membros_graus_historico;
CREATE POLICY "Leitura para autenticados" ON public.membros_graus_historico
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Escrita para editores" ON public.membros_graus_historico
  FOR ALL TO authenticated USING (public.can_edit()) WITH CHECK (public.can_edit());

-- Membros: escrita passa a exigir papel de editor (antes qualquer autenticado podia).
DROP POLICY IF EXISTS "Users can insert membros" ON public.membros;
DROP POLICY IF EXISTS "Users can update membros" ON public.membros;
DROP POLICY IF EXISTS "Users can delete membros" ON public.membros;
DROP POLICY IF EXISTS "Escrita para editores" ON public.membros;
CREATE POLICY "Escrita para editores" ON public.membros
  FOR ALL TO authenticated USING (public.can_edit()) WITH CHECK (public.can_edit());
