-- 1. Create the activity_logs table
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- o perfil que disparou
    acao TEXT NOT NULL,         -- INSERT, UPDATE, DELETE
    tabela_afetada TEXT NOT NULL, -- preparos, sessoes, consumos_sessao, etc.
    registro_id BIGINT,         -- o id da linha sendo alterada/inserida
    dados_antigos JSONB,
    dados_novos JSONB,
    mensagem_automatica TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for the log table
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Admins / Super Admins policy (allowing superadmin or admin based on your RBAC, fallback to default auth)
-- Let's make it viewable by authenticated users for now or rely on specific claims:
CREATE POLICY "Admins can view activity logs" 
    ON public.activity_logs 
    FOR SELECT 
    USING (auth.role() = 'authenticated'); -- Pode ajustar de acordo com sua policy de roles.

-- Grants
GRANT ALL ON TABLE public.activity_logs TO authenticated;
GRANT ALL ON TABLE public.activity_logs TO service_role;

-- 2. Create the unified Trigger Function
CREATE OR REPLACE FUNCTION public.log_activity()
RETURNS TRIGGER AS $$
DECLARE
    current_uid UUID;
    v_msg TEXT;
BEGIN
    -- Fetch the user who made the change (Supabase sets auth.uid() automatically via PostgREST)
    current_uid := auth.uid();

    -- Determine action and build an automatic message
    IF (TG_OP = 'INSERT') THEN
        IF (TG_TABLE_NAME = 'sessoes') THEN
            v_msg := 'Nova sessão registrada (' || NEW.tipo || ')';
        ELSIF (TG_TABLE_NAME = 'preparos') THEN
            v_msg := 'Novo preparo registrado (' || NEW.grau || ' - ' || NEW.mestre_preparo || ')';
        ELSIF (TG_TABLE_NAME = 'saidas') THEN
            v_msg := 'Nova saída logada para ' || NEW.destino;
        ELSE
            v_msg := 'Ação adicionada em ' || TG_TABLE_NAME;
        END IF;

        INSERT INTO public.activity_logs (user_id, acao, tabela_afetada, registro_id, dados_novos, mensagem_automatica)
        VALUES (current_uid, TG_OP, TG_TABLE_NAME, NEW.id, row_to_json(NEW)::jsonb, v_msg);
        RETURN NEW;
        
    ELSIF (TG_OP = 'UPDATE') THEN
        IF (TG_TABLE_NAME = 'preparos') THEN
            v_msg := 'Estoque de preparo modificado (' || NEW.grau || ' - ' || NEW.mestre_preparo || ')';
        ELSIF (TG_TABLE_NAME = 'sessoes') THEN
            v_msg := 'Detalhes da Sessão modificados (' || NEW.tipo || ')';
        ELSE
            v_msg := 'Registro atualizado em ' || TG_TABLE_NAME;
        END IF;

        INSERT INTO public.activity_logs (user_id, acao, tabela_afetada, registro_id, dados_antigos, dados_novos, mensagem_automatica)
        VALUES (current_uid, TG_OP, TG_TABLE_NAME, NEW.id, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, v_msg);
        RETURN NEW;
        
    ELSIF (TG_OP = 'DELETE') THEN
        IF (TG_TABLE_NAME = 'sessoes') THEN
            v_msg := 'Sessão apagada (' || OLD.tipo || ')';
        ELSIF (TG_TABLE_NAME = 'preparos') THEN
            v_msg := 'Preparo deletado (' || OLD.grau || ' - ' || OLD.mestre_preparo || ')';
        ELSE
            v_msg := 'Registro removido em ' || TG_TABLE_NAME;
        END IF;

        INSERT INTO public.activity_logs (user_id, acao, tabela_afetada, registro_id, dados_antigos, mensagem_automatica)
        VALUES (current_uid, TG_OP, TG_TABLE_NAME, OLD.id, row_to_json(OLD)::jsonb, v_msg);
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. Attach Triggers to critical tables
DROP TRIGGER IF EXISTS trg_log_preparos ON public.preparos;
CREATE TRIGGER trg_log_preparos
AFTER INSERT OR UPDATE OR DELETE ON public.preparos
FOR EACH ROW EXECUTE FUNCTION public.log_activity();

DROP TRIGGER IF EXISTS trg_log_sessoes ON public.sessoes;
CREATE TRIGGER trg_log_sessoes
AFTER INSERT OR UPDATE OR DELETE ON public.sessoes
FOR EACH ROW EXECUTE FUNCTION public.log_activity();

DROP TRIGGER IF EXISTS trg_log_consumos_sessao ON public.consumos_sessao;
CREATE TRIGGER trg_log_consumos_sessao
AFTER INSERT OR UPDATE OR DELETE ON public.consumos_sessao
FOR EACH ROW EXECUTE FUNCTION public.log_activity();

DROP TRIGGER IF EXISTS trg_log_saidas ON public.saidas;
CREATE TRIGGER trg_log_saidas
AFTER INSERT OR UPDATE OR DELETE ON public.saidas
FOR EACH ROW EXECUTE FUNCTION public.log_activity();
