-- Create membros table
CREATE TABLE IF NOT EXISTS "public"."membros" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" text NOT NULL,
    "grau" text,
    "tipo_vinculo" text DEFAULT 'Local'::text,
    "nucleo_origem" text,
    "ativo" boolean DEFAULT true,
    "user_id" uuid REFERENCES auth.users,
    "created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "membros_tipo_vinculo_check" CHECK (("tipo_vinculo" = ANY (ARRAY['Local'::"text", 'Visitante'::"text"])))
);

-- Enable RLS
ALTER TABLE "public"."membros" ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can read all membros" ON "public"."membros" FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can insert membros" ON "public"."membros" FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can update membros" ON "public"."membros" FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Users can delete membros" ON "public"."membros" FOR DELETE USING (auth.role() = 'authenticated');

-- Grant permissions to authenticated users
GRANT ALL ON TABLE "public"."membros" TO authenticated;
GRANT ALL ON SEQUENCE "public"."membros_id_seq" TO authenticated;

-- Add foreign key columns to existing tables for gradual migration
-- Sessoes
ALTER TABLE "public"."sessoes" ADD COLUMN IF NOT EXISTS "dirigente_id" bigint REFERENCES "public"."membros"("id") ON DELETE SET NULL;
ALTER TABLE "public"."sessoes" ADD COLUMN IF NOT EXISTS "explanador_id" bigint REFERENCES "public"."membros"("id") ON DELETE SET NULL;
ALTER TABLE "public"."sessoes" ADD COLUMN IF NOT EXISTS "leitor_documentos_id" bigint REFERENCES "public"."membros"("id") ON DELETE SET NULL;

-- Preparos
ALTER TABLE "public"."preparos" ADD COLUMN IF NOT EXISTS "mestre_preparo_id" bigint REFERENCES "public"."membros"("id") ON DELETE SET NULL;

-- Leituras
ALTER TABLE "public"."leituras" ADD COLUMN IF NOT EXISTS "leitor_id" bigint REFERENCES "public"."membros"("id") ON DELETE SET NULL;
